version: 2

updates:
  - package-ecosystem: npm
    directory: /web
    schedule:
      interval: weekly
      day: monday
      time: '05:15'
      timezone: Europe/Prague
    open-pull-requests-limit: 5
    groups:
      web-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      web-security:
        applies-to: security-updates
        patterns:
          - '*'

  - package-ecosystem: npm
    directory: /mobile
    schedule:
      interval: weekly
      day: monday
      time: '05:30'
      timezone: Europe/Prague
    open-pull-requests-limit: 5
    groups:
      mobile-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      mobile-security:
        applies-to: security-updates
        patterns:
          - '*'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: '05:45'
      timezone: Europe/Prague
    open-pull-requests-limit: 5
    groups:
      actions-minor-patch:
        applies-to: version-updates
        patterns:
          - '*'
        update-types:
          - minor
          - patch
      actions-security:
        applies-to: security-updates
        patterns:
          - '*'
