name: Web CI

on:
  push:
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm ci

      - name: Generate Supabase types
        run: npx supabase gen types typescript --project-id vzzrrfllzmxfedhphtcv > src/types/supabase.ts
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}

      - run: npm run lint
      - run: npm run build
